import "./globals.css";
import Header from "@/src/components/header/Header";
import Footer from "@/src/components/footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const hadFooter = true;

  return (
    <html lang="en">
      <body className="w-full max-w-7xl mx-auto px-5 pb-5">
        <Header></Header>
        <main className="flex flex-col">{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}
